import psycopg2

conn = psycopg2.connect(
  host='localhost',
  user='',
    dbname='',
    password='',
    port=5432,
    connect_timeout=500)
cur = conn.cursor()

# application_test =============================================================
cmd1 = """
DROP TABLE IF EXISTS kaggle_cdr.application_test;
CREATE TABLE kaggle_cdr.application_test
(
    SK_ID_CURR numeric,
    NAME_CONTRACT_TYPE text,
    CODE_GENDER text,
    FLAG_OWN_CAR text,
    FLAG_OWN_REALTY text,
    CNT_CHILDREN numeric,
    AMT_INCOME_TOTAL numeric,
    AMT_CREDIT numeric,
    AMT_ANNUITY numeric,
    AMT_GOODS_PRICE numeric,
    NAME_TYPE_SUITE text,
    NAME_INCOME_TYPE text,
    NAME_EDUCATION_TYPE text,
    NAME_FAMILY_STATUS text,
    NAME_HOUSING_TYPE text,
    REGION_POPULATION_RELATIVE numeric,
    DAYS_BIRTH numeric,
    DAYS_EMPLOYED numeric,
    DAYS_REGISTRATION numeric,
    DAYS_ID_PUBLISH numeric,
    OWN_CAR_AGE text,
    FLAG_MOBIL numeric,
    FLAG_EMP_PHONE numeric,
    FLAG_WORK_PHONE numeric,
    FLAG_CONT_MOBILE numeric,
    FLAG_PHONE numeric,
    FLAG_EMAIL numeric,
    OCCUPATION_TYPE text,
    CNT_FAM_MEMBERS numeric,
    REGION_RATING_CLIENT numeric,
    REGION_RATING_CLIENT_W_CITY numeric,
    WEEKDAY_APPR_PROCESS_START text,
    HOUR_APPR_PROCESS_START numeric,
    REG_REGION_NOT_LIVE_REGION numeric,
    REG_REGION_NOT_WORK_REGION numeric,
    LIVE_REGION_NOT_WORK_REGION numeric,
    REG_CITY_NOT_LIVE_CITY numeric,
    REG_CITY_NOT_WORK_CITY numeric,
    LIVE_CITY_NOT_WORK_CITY numeric,
    ORGANIZATION_TYPE text,
    EXT_SOURCE_1 text,
    EXT_SOURCE_2 numeric,
    EXT_SOURCE_3 text,
    APARTMENTS_AVG text,
    BASEMENTAREA_AVG text,
    YEARS_BEGINEXPLUATATION_AVG text,
    YEARS_BUILD_AVG text,
    COMMONAREA_AVG text,
    ELEVATORS_AVG text,
    ENTRANCES_AVG text,
    FLOORSMAX_AVG text,
    FLOORSMIN_AVG text,
    LANDAREA_AVG text,
    LIVINGAPARTMENTS_AVG text,
    LIVINGAREA_AVG text,
    NONLIVINGAPARTMENTS_AVG text,
    NONLIVINGAREA_AVG text,
    APARTMENTS_MODE text,
    BASEMENTAREA_MODE text,
    YEARS_BEGINEXPLUATATION_MODE text,
    YEARS_BUILD_MODE text,
    COMMONAREA_MODE text,
    ELEVATORS_MODE text,
    ENTRANCES_MODE text,
    FLOORSMAX_MODE text,
    FLOORSMIN_MODE text,
    LANDAREA_MODE text,
    LIVINGAPARTMENTS_MODE text,
    LIVINGAREA_MODE text,
    NONLIVINGAPARTMENTS_MODE text,
    NONLIVINGAREA_MODE text,
    APARTMENTS_MEDI text,
    BASEMENTAREA_MEDI text,
    YEARS_BEGINEXPLUATATION_MEDI text,
    YEARS_BUILD_MEDI text,
    COMMONAREA_MEDI text,
    ELEVATORS_MEDI text,
    ENTRANCES_MEDI text,
    FLOORSMAX_MEDI text,
    FLOORSMIN_MEDI text,
    LANDAREA_MEDI text,
    LIVINGAPARTMENTS_MEDI text,
    LIVINGAREA_MEDI text,
    NONLIVINGAPARTMENTS_MEDI text,
    NONLIVINGAREA_MEDI text,
    FONDKAPREMONT_MODE text,
    HOUSETYPE_MODE text,
    TOTALAREA_MODE text,
    WALLSMATERIAL_MODE text,
    EMERGENCYSTATE_MODE text,
    OBS_30_CNT_SOCIAL_CIRCLE text,
    DEF_30_CNT_SOCIAL_CIRCLE text,
    OBS_60_CNT_SOCIAL_CIRCLE text,
    DEF_60_CNT_SOCIAL_CIRCLE text,
    DAYS_LAST_PHONE_CHANGE numeric,
    FLAG_DOCUMENT_2 numeric,
    FLAG_DOCUMENT_3 numeric,
    FLAG_DOCUMENT_4 numeric,
    FLAG_DOCUMENT_5 numeric,
    FLAG_DOCUMENT_6 numeric,
    FLAG_DOCUMENT_7 numeric,
    FLAG_DOCUMENT_8 numeric,
    FLAG_DOCUMENT_9 numeric,
    FLAG_DOCUMENT_10 numeric,
    FLAG_DOCUMENT_11 numeric,
    FLAG_DOCUMENT_12 numeric,
    FLAG_DOCUMENT_13 numeric,
    FLAG_DOCUMENT_14 numeric,
    FLAG_DOCUMENT_15 numeric,
    FLAG_DOCUMENT_16 numeric,
    FLAG_DOCUMENT_17 numeric,
    FLAG_DOCUMENT_18 numeric,
    FLAG_DOCUMENT_19 numeric,
    FLAG_DOCUMENT_20 numeric,
    FLAG_DOCUMENT_21 numeric,
    AMT_REQ_CREDIT_BUREAU_HOUR text,
    AMT_REQ_CREDIT_BUREAU_DAY text,
    AMT_REQ_CREDIT_BUREAU_WEEK text,
    AMT_REQ_CREDIT_BUREAU_MON text,
    AMT_REQ_CREDIT_BUREAU_QRT text,
    AMT_REQ_CREDIT_BUREAU_YEAR text,
    SK_ID_BUREAU integer,
    MONTHS_BALANCE text,
    STATUS text);
"""

cmd1_1 = """
COPY kaggle_cdr.application_test(SK_ID_CURR, NAME_CONTRACT_TYPE ,CODE_GENDER ,FLAG_OWN_CAR ,FLAG_OWN_REALTY ,CNT_CHILDREN ,AMT_INCOME_TOTAL ,AMT_CREDIT ,AMT_ANNUITY ,AMT_GOODS_PRICE ,NAME_TYPE_SUITE ,NAME_INCOME_TYPE ,NAME_EDUCATION_TYPE ,NAME_FAMILY_STATUS ,NAME_HOUSING_TYPE ,REGION_POPULATION_RELATIVE ,DAYS_BIRTH ,DAYS_EMPLOYED ,DAYS_REGISTRATION ,DAYS_ID_PUBLISH ,OWN_CAR_AGE ,FLAG_MOBIL ,FLAG_EMP_PHONE ,FLAG_WORK_PHONE ,FLAG_CONT_MOBILE ,FLAG_PHONE ,FLAG_EMAIL ,OCCUPATION_TYPE ,CNT_FAM_MEMBERS ,REGION_RATING_CLIENT ,REGION_RATING_CLIENT_W_CITY ,WEEKDAY_APPR_PROCESS_START ,HOUR_APPR_PROCESS_START ,REG_REGION_NOT_LIVE_REGION ,REG_REGION_NOT_WORK_REGION ,LIVE_REGION_NOT_WORK_REGION ,REG_CITY_NOT_LIVE_CITY ,REG_CITY_NOT_WORK_CITY ,LIVE_CITY_NOT_WORK_CITY ,ORGANIZATION_TYPE ,EXT_SOURCE_1 ,EXT_SOURCE_2 ,EXT_SOURCE_3 ,APARTMENTS_AVG ,BASEMENTAREA_AVG ,YEARS_BEGINEXPLUATATION_AVG ,YEARS_BUILD_AVG ,COMMONAREA_AVG ,ELEVATORS_AVG ,ENTRANCES_AVG ,FLOORSMAX_AVG ,FLOORSMIN_AVG ,LANDAREA_AVG ,LIVINGAPARTMENTS_AVG ,LIVINGAREA_AVG ,NONLIVINGAPARTMENTS_AVG ,NONLIVINGAREA_AVG ,APARTMENTS_MODE ,BASEMENTAREA_MODE ,YEARS_BEGINEXPLUATATION_MODE ,YEARS_BUILD_MODE ,COMMONAREA_MODE ,ELEVATORS_MODE ,ENTRANCES_MODE ,FLOORSMAX_MODE ,FLOORSMIN_MODE ,LANDAREA_MODE ,LIVINGAPARTMENTS_MODE ,LIVINGAREA_MODE ,NONLIVINGAPARTMENTS_MODE ,NONLIVINGAREA_MODE ,APARTMENTS_MEDI ,BASEMENTAREA_MEDI ,YEARS_BEGINEXPLUATATION_MEDI ,YEARS_BUILD_MEDI ,COMMONAREA_MEDI ,ELEVATORS_MEDI ,ENTRANCES_MEDI ,FLOORSMAX_MEDI ,FLOORSMIN_MEDI ,LANDAREA_MEDI ,LIVINGAPARTMENTS_MEDI ,LIVINGAREA_MEDI ,NONLIVINGAPARTMENTS_MEDI ,NONLIVINGAREA_MEDI ,FONDKAPREMONT_MODE ,HOUSETYPE_MODE ,TOTALAREA_MODE ,WALLSMATERIAL_MODE ,EMERGENCYSTATE_MODE ,OBS_30_CNT_SOCIAL_CIRCLE ,DEF_30_CNT_SOCIAL_CIRCLE ,OBS_60_CNT_SOCIAL_CIRCLE ,DEF_60_CNT_SOCIAL_CIRCLE ,DAYS_LAST_PHONE_CHANGE ,FLAG_DOCUMENT_2 ,FLAG_DOCUMENT_3 ,FLAG_DOCUMENT_4 ,FLAG_DOCUMENT_5 ,FLAG_DOCUMENT_6 ,FLAG_DOCUMENT_7 ,FLAG_DOCUMENT_8 ,FLAG_DOCUMENT_9 ,FLAG_DOCUMENT_10 ,FLAG_DOCUMENT_11 ,FLAG_DOCUMENT_12 ,FLAG_DOCUMENT_13 ,FLAG_DOCUMENT_14 ,FLAG_DOCUMENT_15 ,FLAG_DOCUMENT_16 ,FLAG_DOCUMENT_17 ,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19 ,FLAG_DOCUMENT_20 ,FLAG_DOCUMENT_21 ,AMT_REQ_CREDIT_BUREAU_HOUR ,AMT_REQ_CREDIT_BUREAU_DAY ,AMT_REQ_CREDIT_BUREAU_WEEK ,AMT_REQ_CREDIT_BUREAU_MON ,AMT_REQ_CREDIT_BUREAU_QRT ,AMT_REQ_CREDIT_BUREAU_YEAR) 
    FROM '/Users/apple/Desktop/STUDY/house credit 1/all/application_test.csv' DELIMITER ',' CSV HEADER;"""

# cur.execute(cmd1)
# conn.commit()
# cur.execute(cmd1_1)
# conn.commit()


cmd2 = """
DROP TABLE IF EXISTS kaggle_cdr.application_train;
CREATE TABLE kaggle_cdr.application_train
(
    SK_ID_CURR numeric,
    TARGET numeric,
    NAME_CONTRACT_TYPE text,
    CODE_GENDER text,
    FLAG_OWN_CAR text,
    FLAG_OWN_REALTY text,
    CNT_CHILDREN numeric,
    AMT_INCOME_TOTAL numeric,
    AMT_CREDIT numeric,
    AMT_ANNUITY numeric,
    AMT_GOODS_PRICE numeric,
    NAME_TYPE_SUITE text,
    NAME_INCOME_TYPE text,
    NAME_EDUCATION_TYPE text,
    NAME_FAMILY_STATUS text,
    NAME_HOUSING_TYPE text,
    REGION_POPULATION_RELATIVE numeric,
    DAYS_BIRTH numeric,
    DAYS_EMPLOYED numeric,
    DAYS_REGISTRATION numeric,
    DAYS_ID_PUBLISH numeric,
    OWN_CAR_AGE text,
    FLAG_MOBIL numeric,
    FLAG_EMP_PHONE numeric,
    FLAG_WORK_PHONE numeric,
    FLAG_CONT_MOBILE numeric,
    FLAG_PHONE numeric,
    FLAG_EMAIL numeric,
    OCCUPATION_TYPE text,
    CNT_FAM_MEMBERS numeric,
    REGION_RATING_CLIENT numeric,
    REGION_RATING_CLIENT_W_CITY numeric,
    WEEKDAY_APPR_PROCESS_START text,
    HOUR_APPR_PROCESS_START numeric,
    REG_REGION_NOT_LIVE_REGION numeric,
    REG_REGION_NOT_WORK_REGION numeric,
    LIVE_REGION_NOT_WORK_REGION numeric,
    REG_CITY_NOT_LIVE_CITY numeric,
    REG_CITY_NOT_WORK_CITY numeric,
    LIVE_CITY_NOT_WORK_CITY numeric,
    ORGANIZATION_TYPE text,
    EXT_SOURCE_1 text,
    EXT_SOURCE_2 numeric,
    EXT_SOURCE_3 text,
    APARTMENTS_AVG text,
    BASEMENTAREA_AVG text,
    YEARS_BEGINEXPLUATATION_AVG text,
    YEARS_BUILD_AVG text,
    COMMONAREA_AVG text,
    ELEVATORS_AVG text,
    ENTRANCES_AVG text,
    FLOORSMAX_AVG text,
    FLOORSMIN_AVG text,
    LANDAREA_AVG text,
    LIVINGAPARTMENTS_AVG text,
    LIVINGAREA_AVG text,
    NONLIVINGAPARTMENTS_AVG text,
    NONLIVINGAREA_AVG text,
    APARTMENTS_MODE text,
    BASEMENTAREA_MODE text,
    YEARS_BEGINEXPLUATATION_MODE text,
    YEARS_BUILD_MODE text,
    COMMONAREA_MODE text,
    ELEVATORS_MODE text,
    ENTRANCES_MODE text,
    FLOORSMAX_MODE text,
    FLOORSMIN_MODE text,
    LANDAREA_MODE text,
    LIVINGAPARTMENTS_MODE text,
    LIVINGAREA_MODE text,
    NONLIVINGAPARTMENTS_MODE text,
    NONLIVINGAREA_MODE text,
    APARTMENTS_MEDI text,
    BASEMENTAREA_MEDI text,
    YEARS_BEGINEXPLUATATION_MEDI text,
    YEARS_BUILD_MEDI text,
    COMMONAREA_MEDI text,
    ELEVATORS_MEDI text,
    ENTRANCES_MEDI text,
    FLOORSMAX_MEDI text,
    FLOORSMIN_MEDI text,
    LANDAREA_MEDI text,
    LIVINGAPARTMENTS_MEDI text,
    LIVINGAREA_MEDI text,
    NONLIVINGAPARTMENTS_MEDI text,
    NONLIVINGAREA_MEDI text,
    FONDKAPREMONT_MODE text,
    HOUSETYPE_MODE text,
    TOTALAREA_MODE text,
    WALLSMATERIAL_MODE text,
    EMERGENCYSTATE_MODE text,
    OBS_30_CNT_SOCIAL_CIRCLE text,
    DEF_30_CNT_SOCIAL_CIRCLE text,
    OBS_60_CNT_SOCIAL_CIRCLE text,
    DEF_60_CNT_SOCIAL_CIRCLE text,
    DAYS_LAST_PHONE_CHANGE numeric,
    FLAG_DOCUMENT_2 numeric,
    FLAG_DOCUMENT_3 numeric,
    FLAG_DOCUMENT_4 numeric,
    FLAG_DOCUMENT_5 numeric,
    FLAG_DOCUMENT_6 numeric,
    FLAG_DOCUMENT_7 numeric,
    FLAG_DOCUMENT_8 numeric,
    FLAG_DOCUMENT_9 numeric,
    FLAG_DOCUMENT_10 numeric,
    FLAG_DOCUMENT_11 numeric,
    FLAG_DOCUMENT_12 numeric,
    FLAG_DOCUMENT_13 numeric,
    FLAG_DOCUMENT_14 numeric,
    FLAG_DOCUMENT_15 numeric,
    FLAG_DOCUMENT_16 numeric,
    FLAG_DOCUMENT_17 numeric,
    FLAG_DOCUMENT_18 numeric,
    FLAG_DOCUMENT_19 numeric,
    FLAG_DOCUMENT_20 numeric,
    FLAG_DOCUMENT_21 numeric,
    AMT_REQ_CREDIT_BUREAU_HOUR text,
    AMT_REQ_CREDIT_BUREAU_DAY text,
    AMT_REQ_CREDIT_BUREAU_WEEK text,
    AMT_REQ_CREDIT_BUREAU_MON text,
    AMT_REQ_CREDIT_BUREAU_QRT text,
    AMT_REQ_CREDIT_BUREAU_YEAR text,
    SK_ID_BUREAU integer,
    MONTHS_BALANCE text,
    STATUS text
);
"""

cmd2_1 = """ 
    COPY kaggle_cdr.application_train(SK_ID_CURR, TARGET, NAME_CONTRACT_TYPE ,CODE_GENDER ,FLAG_OWN_CAR ,FLAG_OWN_REALTY ,CNT_CHILDREN ,AMT_INCOME_TOTAL ,AMT_CREDIT ,AMT_ANNUITY ,AMT_GOODS_PRICE ,NAME_TYPE_SUITE ,NAME_INCOME_TYPE ,NAME_EDUCATION_TYPE ,NAME_FAMILY_STATUS ,NAME_HOUSING_TYPE ,REGION_POPULATION_RELATIVE ,DAYS_BIRTH ,DAYS_EMPLOYED ,DAYS_REGISTRATION ,DAYS_ID_PUBLISH ,OWN_CAR_AGE ,FLAG_MOBIL ,FLAG_EMP_PHONE ,FLAG_WORK_PHONE ,FLAG_CONT_MOBILE ,FLAG_PHONE ,FLAG_EMAIL ,OCCUPATION_TYPE ,CNT_FAM_MEMBERS ,REGION_RATING_CLIENT ,REGION_RATING_CLIENT_W_CITY ,WEEKDAY_APPR_PROCESS_START ,HOUR_APPR_PROCESS_START ,REG_REGION_NOT_LIVE_REGION ,REG_REGION_NOT_WORK_REGION ,LIVE_REGION_NOT_WORK_REGION ,REG_CITY_NOT_LIVE_CITY ,REG_CITY_NOT_WORK_CITY ,LIVE_CITY_NOT_WORK_CITY ,ORGANIZATION_TYPE ,EXT_SOURCE_1 ,EXT_SOURCE_2 ,EXT_SOURCE_3 ,APARTMENTS_AVG ,BASEMENTAREA_AVG ,YEARS_BEGINEXPLUATATION_AVG ,YEARS_BUILD_AVG ,COMMONAREA_AVG ,ELEVATORS_AVG ,ENTRANCES_AVG ,FLOORSMAX_AVG ,FLOORSMIN_AVG ,LANDAREA_AVG ,LIVINGAPARTMENTS_AVG ,LIVINGAREA_AVG ,NONLIVINGAPARTMENTS_AVG ,NONLIVINGAREA_AVG ,APARTMENTS_MODE ,BASEMENTAREA_MODE ,YEARS_BEGINEXPLUATATION_MODE ,YEARS_BUILD_MODE ,COMMONAREA_MODE ,ELEVATORS_MODE ,ENTRANCES_MODE ,FLOORSMAX_MODE ,FLOORSMIN_MODE ,LANDAREA_MODE ,LIVINGAPARTMENTS_MODE ,LIVINGAREA_MODE ,NONLIVINGAPARTMENTS_MODE ,NONLIVINGAREA_MODE ,APARTMENTS_MEDI ,BASEMENTAREA_MEDI ,YEARS_BEGINEXPLUATATION_MEDI ,YEARS_BUILD_MEDI ,COMMONAREA_MEDI ,ELEVATORS_MEDI ,ENTRANCES_MEDI ,FLOORSMAX_MEDI ,FLOORSMIN_MEDI ,LANDAREA_MEDI ,LIVINGAPARTMENTS_MEDI ,LIVINGAREA_MEDI ,NONLIVINGAPARTMENTS_MEDI ,NONLIVINGAREA_MEDI ,FONDKAPREMONT_MODE ,HOUSETYPE_MODE ,TOTALAREA_MODE ,WALLSMATERIAL_MODE ,EMERGENCYSTATE_MODE ,OBS_30_CNT_SOCIAL_CIRCLE ,DEF_30_CNT_SOCIAL_CIRCLE ,OBS_60_CNT_SOCIAL_CIRCLE ,DEF_60_CNT_SOCIAL_CIRCLE ,DAYS_LAST_PHONE_CHANGE ,FLAG_DOCUMENT_2 ,FLAG_DOCUMENT_3 ,FLAG_DOCUMENT_4 ,FLAG_DOCUMENT_5 ,FLAG_DOCUMENT_6 ,FLAG_DOCUMENT_7 ,FLAG_DOCUMENT_8 ,FLAG_DOCUMENT_9 ,FLAG_DOCUMENT_10 ,FLAG_DOCUMENT_11 ,FLAG_DOCUMENT_12 ,FLAG_DOCUMENT_13 ,FLAG_DOCUMENT_14 ,FLAG_DOCUMENT_15 ,FLAG_DOCUMENT_16 ,FLAG_DOCUMENT_17 ,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19 ,FLAG_DOCUMENT_20 ,FLAG_DOCUMENT_21 ,AMT_REQ_CREDIT_BUREAU_HOUR ,AMT_REQ_CREDIT_BUREAU_DAY ,AMT_REQ_CREDIT_BUREAU_WEEK ,AMT_REQ_CREDIT_BUREAU_MON ,AMT_REQ_CREDIT_BUREAU_QRT ,AMT_REQ_CREDIT_BUREAU_YEAR)
FROM '/Users/apple/Desktop/STUDY/house credit 1/all/application_train.csv' DELIMITER ',' CSV HEADER;"""

# cur.execute(cmd2)
# conn.commit()
# cur.execute(cmd2_1)
# conn.commit()


#application bureau =============================================================
cmd3 = """
DROP TABLE IF EXISTS kaggle_cdr.bureau;
CREATE TABLE kaggle_cdr.bureau
(
    SK_ID_CURR numeric,
    SK_ID_BUREAU numeric,
    CREDIT_ACTIVE text,
    CREDIT_CURRENCY text,
    DAYS_CREDIT numeric,
    CREDIT_DAY_OVERDUE numeric,
    DAYS_CREDIT_ENDDATE text,
    DAYS_ENDDATE_FACT text,
    AMT_CREDIT_MAX_OVERDUE text,
    CNT_CREDIT_PROLONG numeric,
    AMT_CREDIT_SUM numeric,
    AMT_CREDIT_SUM_DEBT text,
    AMT_CREDIT_SUM_LIMIT text,
    AMT_CREDIT_SUM_OVERDUE numeric,
    CREDIT_TYPE text,
    DAYS_CREDIT_UPDATE numeric,
    AMT_ANNUITY text
);
"""

cmd3_1 = """ 
    COPY kaggle_cdr.bureau(SK_ID_CURR, SK_ID_BUREAU, CREDIT_ACTIVE, CREDIT_CURRENCY, DAYS_CREDIT, CREDIT_DAY_OVERDUE, DAYS_CREDIT_ENDDATE, DAYS_ENDDATE_FACT, AMT_CREDIT_MAX_OVERDUE, CNT_CREDIT_PROLONG, AMT_CREDIT_SUM, AMT_CREDIT_SUM_DEBT, AMT_CREDIT_SUM_LIMIT, AMT_CREDIT_SUM_OVERDUE, CREDIT_TYPE, DAYS_CREDIT_UPDATE, AMT_ANNUITY)
FROM '/Users/apple/Desktop/STUDY/house credit 1/all/bureau.csv' DELIMITER ',' CSV HEADER;"""

# cur.execute(cmd3)
# conn.commit()
# cur.execute(cmd3_1)
# conn.commit()

#application bureau_balance =============================================================
cmd4 = """
DROP TABLE IF EXISTS kaggle_cdr.bureau_balance;
CREATE TABLE kaggle_cdr.bureau_balance
(
    SK_ID_BUREAU numeric,
    MONTHS_BALANCE text,
    STATUS text
);
"""

cmd4_1 = """ 
COPY kaggle_cdr.bureau_balance(SK_ID_BUREAU, MONTHS_BALANCE, STATUS) 
FROM '/Users/apple/Desktop/STUDY/house credit 1/all/bureau_balance.csv' DELIMITER ',' CSV HEADER;"""

# cur.execute(cmd4)
# conn.commit()
# cur.execute(cmd4_1)
# conn.commit()

#application bureau_balance =============================================================
cmd5 = """
DROP TABLE IF EXISTS kaggle_cdr.credit_card_balance;
CREATE TABLE kaggle_cdr.credit_card_balance
(
    SK_ID_PREV numeric,
    SK_ID_CURR numeric,
    MONTHS_BALANCE numeric,
    AMT_BALANCE numeric,
    AMT_CREDIT_LIMIT_ACTUAL numeric,
    AMT_DRAWINGS_ATM_CURRENT text,
    AMT_DRAWINGS_CURRENT numeric,
    AMT_DRAWINGS_OTHER_CURRENT text,
    AMT_DRAWINGS_POS_CURRENT text,
    AMT_INST_MIN_REGULARITY numeric,
    AMT_PAYMENT_CURRENT text,
    AMT_PAYMENT_TOTAL_CURRENT numeric,
    AMT_RECEIVABLE_PRINCIPAL numeric,
    AMT_RECIVABLE numeric,
    AMT_TOTAL_RECEIVABLE numeric,
    CNT_DRAWINGS_ATM_CURRENT text,
    CNT_DRAWINGS_CURRENT numeric,
    CNT_DRAWINGS_OTHER_CURRENT text,
    CNT_DRAWINGS_POS_CURRENT text,
    CNT_INSTALMENT_MATURE_CUM numeric,
    NAME_CONTRACT_STATUS text,
    SK_DPD numeric,
    SK_DPD_DEF numeric
)
"""

cmd5_1 = """ 
    COPY kaggle_cdr.credit_card_balance(SK_ID_PREV, SK_ID_CURR, MONTHS_BALANCE, AMT_BALANCE, AMT_CREDIT_LIMIT_ACTUAL, AMT_DRAWINGS_ATM_CURRENT, AMT_DRAWINGS_CURRENT, AMT_DRAWINGS_OTHER_CURRENT, AMT_DRAWINGS_POS_CURRENT, AMT_INST_MIN_REGULARITY, AMT_PAYMENT_CURRENT, AMT_PAYMENT_TOTAL_CURRENT, AMT_RECEIVABLE_PRINCIPAL, AMT_RECIVABLE, AMT_TOTAL_RECEIVABLE, CNT_DRAWINGS_ATM_CURRENT, CNT_DRAWINGS_CURRENT, CNT_DRAWINGS_OTHER_CURRENT, CNT_DRAWINGS_POS_CURRENT, CNT_INSTALMENT_MATURE_CUM, NAME_CONTRACT_STATUS, SK_DPD, SK_DPD_DEF)
FROM '/Users/apple/Desktop/STUDY/house credit 1/all/credit_card_balance.csv' DELIMITER ',' CSV HEADER;"""

# cur.execute(cmd5)
# conn.commit()
# cur.execute(cmd5_1)
# conn.commit()


#HomeCredit_columns_description =============================================================
cmd6 = """
DROP TABLE IF EXISTS kaggle_cdr.home_credit_columns_description;
CREATE TABLE kaggle_cdr.home_credit_columns_description
(
    Record_index numeric,
    Table_name text,
    Row text,
    Description text,
    Special text
)
"""

cmd6_1 = """ 
    COPY kaggle_cdr.home_credit_columns_description(Record_index, Table_name, Row, Description, Special)
FROM '/Users/apple/Desktop/STUDY/house credit 1/all/HomeCredit_columns_description.csv' DELIMITER ',' CSV HEADER;"""

# cur.execute(cmd6)
# conn.commit()
# cur.execute(cmd6_1)
# conn.commit()

#installments_payments =============================================================
cmd7 = """
DROP TABLE IF EXISTS kaggle_cdr.installments_payments;
CREATE TABLE kaggle_cdr.installments_payments
(
    SK_ID_PREV numeric,
    SK_ID_CURR numeric,
    NUM_INSTALMENT_VERSION numeric,
    NUM_INSTALMENT_NUMBER numeric,
    DAYS_INSTALMENT numeric,
    DAYS_ENTRY_PAYMENT numeric,
    AMT_INSTALMENT numeric,
    AMT_PAYMENT numeric
)
"""

cmd7_1 = """ 
    COPY kaggle_cdr.installments_payments(SK_ID_PREV, SK_ID_CURR, NUM_INSTALMENT_VERSION, NUM_INSTALMENT_NUMBER, DAYS_INSTALMENT, DAYS_ENTRY_PAYMENT, AMT_INSTALMENT, AMT_PAYMENT)
FROM '/Users/apple/Desktop/STUDY/house credit 1/all/installments_payments.csv' DELIMITER ',' CSV HEADER;"""

# cur.execute(cmd7)
# conn.commit()
# cur.execute(cmd7_1)
# conn.commit()

#POS_CASH_balance =============================================================
cmd8 = """
DROP TABLE IF EXISTS kaggle_cdr.pos_cash_balance;
CREATE TABLE kaggle_cdr.pos_cash_balance
(
    SK_ID_PREV numeric,
    SK_ID_CURR numeric,
    MONTHS_BALANCE numeric,
    CNT_INSTALMENT numeric,
    CNT_INSTALMENT_FUTURE numeric,
    NAME_CONTRACT_STATUS text,
    SK_DPD numeric,
    SK_DPD_DEF numeric
)
"""

cmd8_1 = """ 
    COPY kaggle_cdr.pos_cash_balance(SK_ID_PREV, SK_ID_CURR, MONTHS_BALANCE, CNT_INSTALMENT, CNT_INSTALMENT_FUTURE, NAME_CONTRACT_STATUS, SK_DPD, SK_DPD_DEF)
FROM '/Users/apple/Desktop/STUDY/house credit 1/all/POS_CASH_balance.csv' DELIMITER ',' CSV HEADER;"""

# cur.execute(cmd8)
# conn.commit()
# cur.execute(cmd8_1)
# conn.commit()

#previous_application=============================================================
cmd9 = """
DROP TABLE IF EXISTS kaggle_cdr.previous_application;
CREATE TABLE kaggle_cdr.previous_application
(
    SK_ID_PREV numeric,
    SK_ID_CURR numeric,
    NAME_CONTRACT_TYPE text,
    AMT_ANNUITY text,
    AMT_APPLICATION numeric,
    AMT_CREDIT numeric,
    AMT_DOWN_PAYMENT text,
    AMT_GOODS_PRICE text,
    WEEKDAY_APPR_PROCESS_START text,
    HOUR_APPR_PROCESS_START numeric,
    FLAG_LAST_APPL_PER_CONTRACT text,
    NFLAG_LAST_APPL_IN_DAY numeric,
    RATE_DOWN_PAYMENT text,
    RATE_INTEREST_PRIMARY text,
    RATE_INTEREST_PRIVILEGED text,
    NAME_CASH_LOAN_PURPOSE text,
    NAME_CONTRACT_STATUS text,
    DAYS_DECISION numeric,
    NAME_PAYMENT_TYPE text,
    CODE_REJECT_REASON text,
    NAME_TYPE_SUITE text,
    NAME_CLIENT_TYPE text,
    NAME_GOODS_CATEGORY text,
    NAME_PORTFOLIO text,
    NAME_PRODUCT_TYPE text,
    CHANNEL_TYPE text,
    SELLERPLACE_AREA numeric,
    NAME_SELLER_INDUSTRY text,
    CNT_PAYMENT text,
    NAME_YIELD_GROUP text,
    PRODUCT_COMBINATION text,
    DAYS_FIRST_DRAWING text,
    DAYS_FIRST_DUE text,
    DAYS_LAST_DUE_1ST_VERSION text,
    DAYS_LAST_DUE text,
    DAYS_TERMINATION text,
    NFLAG_INSURED_ON_APPROVAL text
)
"""

cmd9_1 = """ 
    COPY kaggle_cdr.previous_application(SK_ID_PREV, SK_ID_CURR, NAME_CONTRACT_TYPE, AMT_ANNUITY, AMT_APPLICATION, AMT_CREDIT, AMT_DOWN_PAYMENT, AMT_GOODS_PRICE, WEEKDAY_APPR_PROCESS_START, HOUR_APPR_PROCESS_START, FLAG_LAST_APPL_PER_CONTRACT, NFLAG_LAST_APPL_IN_DAY, RATE_DOWN_PAYMENT, RATE_INTEREST_PRIMARY, RATE_INTEREST_PRIVILEGED, NAME_CASH_LOAN_PURPOSE, NAME_CONTRACT_STATUS, DAYS_DECISION, NAME_PAYMENT_TYPE, CODE_REJECT_REASON, NAME_TYPE_SUITE, NAME_CLIENT_TYPE, NAME_GOODS_CATEGORY, NAME_PORTFOLIO, NAME_PRODUCT_TYPE, CHANNEL_TYPE, SELLERPLACE_AREA, NAME_SELLER_INDUSTRY, CNT_PAYMENT, NAME_YIELD_GROUP, PRODUCT_COMBINATION, DAYS_FIRST_DRAWING, DAYS_FIRST_DUE, DAYS_LAST_DUE_1ST_VERSION, DAYS_LAST_DUE, DAYS_TERMINATION, NFLAG_INSURED_ON_APPROVAL)
FROM '/Users/apple/Desktop/STUDY/house credit 1/all/previous_application.csv' DELIMITER ',' CSV HEADER;"""

# cur.execute(cmd9)
# conn.commit()
# cur.execute(cmd9_1)
# conn.commit()

#sample_submission =============================================================
cmd10 = """
DROP TABLE IF EXISTS kaggle_cdr.sample_submission;
CREATE TABLE kaggle_cdr.sample_submission
(
    SK_ID_CURR numeric,
    TARGET numeric
)
"""

cmd10_1 = """ 
    COPY kaggle_cdr.sample_submission(SK_ID_CURR, TARGET)
FROM '/Users/apple/Desktop/STUDY/house credit 1/all/sample_submission.csv' DELIMITER ',' CSV HEADER;"""

cur.execute(cmd10)
conn.commit()
cur.execute(cmd10_1)
conn.commit()